//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace BayHelper.Com.Models
{
    public partial class BayHelperEntities : DbContext
    {
        public BayHelperEntities()
            : base("name=BayHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<FinanceDonation> FinanceDonations { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<ResourceDonation> ResourceDonations { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TimeDonation> TimeDonations { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
