//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class Event
    {
        public Event()
        {
            this.Comments = new HashSet<Comment>();
            this.FinanceDonations = new HashSet<FinanceDonation>();
            this.ResourceDonations = new HashSet<ResourceDonation>();
            this.TimeDonations = new HashSet<TimeDonation>();
        }
    
        public int EventID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<byte> Status { get; set; }
        public string LaborDescription { get; set; }
        public string ResourcesDescription { get; set; }
        public Nullable<int> FinanceGoal { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<FinanceDonation> FinanceDonations { get; set; }
        public virtual ICollection<ResourceDonation> ResourceDonations { get; set; }
        public virtual ICollection<TimeDonation> TimeDonations { get; set; }
    }
    
}
