//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class Message
    {
        public int MessageID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Writer { get; set; }
        public Nullable<int> Reciever { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
    
}
