//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class Organization
    {
        public Organization()
        {
            this.Users = new HashSet<User>();
        }
    
        public int OrganizationID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
    
}
