//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class ResourceDonation
    {
        public int ResourceDonationID { get; set; }
        public Nullable<int> ResorceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Location { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual User User { get; set; }
    }
    
}
