//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class Resource
    {
        public Resource()
        {
            this.ResourceDonations = new HashSet<ResourceDonation>();
        }
    
        public int ResourceID { get; set; }
        public string Description { get; set; }
        public string Units { get; set; }
        public Nullable<int> AmountRequired { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<ResourceDonation> ResourceDonations { get; set; }
    }
    
}
