//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class Task
    {
        public Task()
        {
            this.TimeDonations = new HashSet<TimeDonation>();
        }
    
        public int TaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> TimeEstimate { get; set; }
        public Nullable<int> FinanceEstimate { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<TimeDonation> TimeDonations { get; set; }
    }
    
}
