//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BayHelper.Com.Models
{
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Events = new HashSet<Event>();
            this.FinanceDonations = new HashSet<FinanceDonation>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.ResourceDonations = new HashSet<ResourceDonation>();
            this.TimeDonations = new HashSet<TimeDonation>();
        }
    
        public int UserID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Nickname { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> OrganizationUser { get; set; }
        public Nullable<int> OrganizationID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<FinanceDonation> FinanceDonations { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<ResourceDonation> ResourceDonations { get; set; }
        public virtual ICollection<TimeDonation> TimeDonations { get; set; }
    }
    
}
